{"@t":"2020-03-25T17:26:48.1667778Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.5.5.","TimingId":"cd8c091","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:48.1887897Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Umbraco_WebSite","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"C:\\Users\\Ortega\\source\\repos\\Umbraco_WebSite\\Umbraco_WebSite\\","MachineName":"DESKTOP-9M7RJNR","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:48.2785496Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.MainDom","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:48.2795476Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.MainDom","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:49.6575982Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"b8edbf9","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:49.8465033Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":187,"TimingId":"b8edbf9","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:50.3153739Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:50.3153739Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:50.3163716Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4533367Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4533367Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4543341Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4543341Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4553326Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4553326Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4553326Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4553326Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4682963Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from local cache file","TimingId":"3c5c215","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4872463Z","@mt":"Tried to load content from the local cache file but it was empty.","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4872463Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":18,"TimingId":"3c5c215","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.4942273Z","@mt":"Loading content from local db raised warnings, will reload from database.","@l":"Warning","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.5012086Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from local cache file","TimingId":"bdf3eef","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.5012086Z","@mt":"Tried to load media from the local cache file but it was empty.","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.5012086Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":0,"TimingId":"bdf3eef","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.5022062Z","@mt":"Loading media from local db raised warnings, will reload from database.","@l":"Warning","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.5111820Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from database","TimingId":"be271d4","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.7505411Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":238,"TimingId":"be271d4","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.7575228Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from database","TimingId":"4774184","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.8073898Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":50,"TimingId":"4774184","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:51.8931598Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:52.0487435Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:52.1095807Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:52.1933571Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:52.2003400Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":4043,"TimingId":"cd8c091","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bf2ad6d0-e68a-4723-b7bd-e25d3fcd044f"}
{"@t":"2020-03-25T17:26:52.6410482Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":8,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"0988fa3c-ab84-43da-82fc-ee427af58ad5"}
{"@t":"2020-03-25T17:26:52.6420456Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":8,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"0988fa3c-ab84-43da-82fc-ee427af58ad5"}
{"@t":"2020-03-25T17:26:53.3988498Z","@mt":"Umbraco has no content","@l":"Warning","SourceContext":"Umbraco.Web.UmbracoModule","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":8,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN ","HttpRequestNumber":2,"HttpRequestId":"0988fa3c-ab84-43da-82fc-ee427af58ad5"}
{"@t":"2020-03-25T17:29:05.1392683Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username pedromdias27@gmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"c83d74c6-3d75-4874-ac7f-55ec800f7a5a"}
{"@t":"2020-03-25T17:29:05.1402650Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: pedromdias27@gmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"c83d74c6-3d75-4874-ac7f-55ec800f7a5a"}
{"@t":"2020-03-25T17:30:37.4214148Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from database","TimingId":"070738a","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"98e6ef24-f522-4e19-867b-af11989e7094"}
{"@t":"2020-03-25T17:30:37.7036697Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":281,"TimingId":"070738a","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"98e6ef24-f522-4e19-867b-af11989e7094"}
{"@t":"2020-03-25T17:30:37.7066528Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from database","TimingId":"40256d9","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"98e6ef24-f522-4e19-867b-af11989e7094"}
{"@t":"2020-03-25T17:30:37.7395643Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":33,"TimingId":"40256d9","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"98e6ef24-f522-4e19-867b-af11989e7094"}
{"@t":"2020-03-25T17:31:39.4405455Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4415441Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4525143Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4565305Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4584990Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4584990Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4594957Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4594957Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4604927Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4604927Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4604927Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4614899Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4624869Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4624869Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4634846Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4644823Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4644823Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4644823Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.4664772Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:39.6180711Z","@mt":"{LogPrefix} Task has failed","@l":"Error","@x":"System.IO.DirectoryNotFoundException: Não foi possível encontrar uma parte do caminho 'C:\\Users\\Ortega\\source\\repos\\Umbraco_WebSite\\Umbraco_WebSite\\App_Data\\TEMP\\FileUploads'.\r\n   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   em System.IO.FileSystemEnumerableIterator`1.CommonInit()\r\n   em System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)\r\n   em System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)\r\n   em System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)\r\n   em Umbraco.Web.Scheduling.TempFileCleanup.CleanupFolder(DirectoryInfo dir) em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\TempFileCleanup.cs:line 56\r\n   em Umbraco.Web.Scheduling.TempFileCleanup.PerformRun() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\TempFileCleanup.cs:line 43\r\n   em Umbraco.Web.Scheduling.RecurringTaskBase.Run() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\RecurringTaskBase.cs:line 47\r\n   em Umbraco.Web.Scheduling.BackgroundTaskRunner`1.<RunAsync>d__40.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\BackgroundTaskRunner.cs:line 549","LogPrefix":"[LogScrubber] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T17:31:43.4497571Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":36,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T17:31:43.4786324Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:43.4786324Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:43.4786324Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:47.4835123Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:47.4835123Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:47.4835123Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:51.4915763Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:51.4915763Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:51.4915763Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:55.4995957Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:59.5119078Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:59.5119078Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:59.5119078Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:59.5128886Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:31:59.5138588Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5233403Z","@mt":"The culture specified {Culture} was not found in any configured sources for this service","@l":"Warning","Culture":"pt-PT","SourceContext":"Umbraco.Core.Services.Implement.LocalizedTextService","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5243127Z","@mt":"Scheduled health check results:","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Folder & File Permissions","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"[folderPermissionsCheckMessage]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"[filePermissionsCheckMessage]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"SMTP Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"SMTP Settings","HealthCheckResult":"Error","HealthCheckMessage":"[smtpMailSettingsHostNotConfigured]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Macro errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Macro errors","HealthCheckResult":"Error","HealthCheckMessage":"[macroErrorModeCheckErrorMessage]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Notification Email Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Notification Email Settings","HealthCheckResult":"Error","HealthCheckMessage":"[notificationEmailsCheckErrorMessage]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Try Skip IIS Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Try Skip IIS Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"[trySkipIisCustomErrorsCheckSuccessMessage]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"[customErrorsCheckSuccessMessage]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Trace Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Trace Mode","HealthCheckResult":"Success","HealthCheckMessage":"[traceModeCheckSuccessMessage]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Debug Compilation Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Debug Compilation Mode","HealthCheckResult":"Success","HealthCheckMessage":"[compilationDebugCheckSuccessMessage]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","HealthCheckResult":"Error","HealthCheckMessage":"[healthCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","HealthCheckResult":"Error","HealthCheckMessage":"[healthCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Content/MIME Sniffing Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Content/MIME Sniffing Protection","HealthCheckResult":"Error","HealthCheckMessage":"[healthCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Excessive Headers","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Excessive Headers","HealthCheckResult":"Warning","HealthCheckMessage":"[httpsCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Click-Jacking Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Click-Jacking Protection","HealthCheckResult":"Error","HealthCheckMessage":"[healthCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"HTTPS Configuration","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"WARN "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"[httpsCheckIsCurrentSchemeHttps]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Info","HealthCheckMessage":"[httpsCheckConfigurationRectifyNotPossible]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:32:03.5253150Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"[healthCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO "}
{"@t":"2020-03-25T17:36:47.4574501Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T17:41:51.4796537Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":40,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T17:46:55.5033285Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T17:48:22.2938960Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: pedromdias27@gmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":55,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"INFO ","HttpRequestNumber":5,"HttpRequestId":"7a375b27-b46a-4864-a494-fa50e8e37cbd"}
{"@t":"2020-03-25T17:51:59.5301441Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T17:57:03.5383068Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":32,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:02:07.5594841Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:07:11.5924719Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":67,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:12:15.6021675Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":46,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:17:19.6210487Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":59,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:22:23.6477181Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":28,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:27:27.6745575Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:32:31.6911252Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":64,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:37:35.7128505Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:42:39.7328150Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:47:43.7443476Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":102,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:52:47.7691362Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T18:57:51.7919963Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:02:55.8186282Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:07:59.8441085Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":104,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:13:03.8707820Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:18:07.9017828Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:23:11.9247358Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:28:15.9621600Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:33:19.9872639Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:38:24.0142057Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:43:28.0435333Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:48:32.0609020Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":104,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:53:36.0853072Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T19:58:40.1141053Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:03:44.1391743Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:08:48.1638032Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":104,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:13:52.1819308Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:18:56.2053758Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:24:00.2308958Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:29:04.2487865Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:34:08.2736957Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:39:12.2941267Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":97,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:44:16.3138225Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:49:20.7072035Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:54:24.7308871Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T20:59:28.7376216Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:04:33.3166197Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":100,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:09:37.4768950Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":48,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:14:41.5075133Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":75,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:19:45.8366809Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":83,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:24:50.3270560Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":86,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:29:54.7235887Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":109,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:34:58.7511419Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":48,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:40:03.1650036Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":108,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:45:07.1800486Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":100,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:50:11.1994309Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":48,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T21:55:15.2374475Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":109,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:00:19.2480628Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:05:23.2659760Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:10:27.2923671Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:15:31.3115312Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:20:35.3238644Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":71,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:25:39.3474155Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":29,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:30:43.3704263Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":95,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:35:47.3973682Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":71,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:40:51.4235278Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":71,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:45:55.4451662Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:50:59.4603147Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-25T22:56:03.4770153Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":17308,"ProcessName":"iisexpress","ThreadId":97,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
