{"@t":"2020-04-13T22:01:18.0851818Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:06:22.1062052Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:11:26.1341806Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:16:30.1536871Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":47,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:21:34.1816183Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":45,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:26:38.2004942Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:31:42.2184990Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:36:46.2289886Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":8,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:41:50.2418949Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":45,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:46:54.2529125Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:51:58.2687322Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":8,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T22:57:02.2904347Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:02:06.3294635Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:07:10.3411140Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:12:14.3774008Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:17:18.4043333Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":45,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:22:22.4221637Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:27:26.4402461Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:32:30.4655488Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":45,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:37:34.4897476Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:42:39.0345030Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:47:43.0464410Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:52:47.5379226Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-13T23:57:51.5624905Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:02:55.5708516Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":45,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:07:59.5856078Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:13:04.0710712Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":45,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:18:08.6780053Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:23:12.7071389Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":36,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:28:17.2147310Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:33:21.6725174Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:38:25.7062142Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:43:29.7418786Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:48:33.7564721Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:53:37.7807828Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T00:58:41.8051989Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:03:45.8247483Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:08:49.8480080Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:13:53.8854337Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:18:57.9121760Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:24:01.9446252Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:29:05.9633460Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:34:09.9789939Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:39:14.0039997Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:44:18.0476093Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:49:22.0608432Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:54:26.0772540Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T01:59:30.1011912Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T02:04:34.1367151Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T02:09:38.1588307Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T02:14:42.1885653Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T02:19:46.1992227Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T02:24:50.2188215Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T18:34:38.7020394Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T18:39:42.7403183Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T18:44:46.7595914Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T18:49:50.7827758Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T18:54:54.8056797Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T18:59:58.8321977Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:05:02.8564038Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:10:06.8779328Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:15:10.9100903Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:20:14.9232449Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:25:18.9353561Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:30:22.9667189Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:35:26.9882214Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:40:31.0080798Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:45:35.0234183Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":86,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:50:39.0481527Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":95,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T19:55:43.0585171Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":50,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:00:47.0800920Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:05:51.1067388Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":45,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:10:55.1339002Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":50,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:15:59.1500408Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":50,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:21:03.1785681Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":55,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:26:07.2062895Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:31:11.2335460Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:36:15.2585326Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":88,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:41:19.2826395Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:46:23.2921026Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:51:27.3154132Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T20:56:31.3348145Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:01:35.3614692Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":86,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:06:39.3717051Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":50,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:11:43.3916627Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:16:47.4156331Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:21:51.4416010Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:26:55.4488201Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":86,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:31:59.4743088Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:37:03.4909268Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:42:07.5179536Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":50,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:47:11.5282364Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:52:15.5595265Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-14T21:57:19.5831770Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":16996,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
